const exercises=[
 {id:'goblet-squat',name:'Goblet Squat',thai:'Goblet Squat',sets:3,reps:'10–12',base:8,unit:'kg',icon:'01'},
 {id:'rdl',name:'Dumbbell Romanian Deadlift',thai:'Dumbbell RDL',sets:3,reps:'10–12',base:8,unit:'kg',icon:'02'},
 {id:'floor-press',name:'Dumbbell Floor Press',thai:'Dumbbell Floor Press',sets:3,reps:'10–12',base:6,unit:'kg',icon:'03'},
 {id:'row',name:'One-arm Dumbbell Row',thai:'One-arm Row',sets:3,reps:'10 / ข้าง',base:8,unit:'kg',icon:'04'},
 {id:'shoulder-press',name:'Dumbbell Shoulder Press',thai:'Shoulder Press',sets:3,reps:'8–10',base:6,unit:'kg',icon:'05'},
 {id:'plank',name:'Plank',thai:'Plank',sets:3,reps:'30–45 วินาที',base:0,unit:'bodyweight',icon:'06'}
];
const DB_KEY='fittrack-db-v2';
const LEGACY_KEY='fittrack-history';
const $=s=>document.querySelector(s), $$=s=>document.querySelectorAll(s);
const defaultDb=()=>({schemaVersion:2,createdAt:new Date().toISOString(),updatedAt:new Date().toISOString(),settings:{baseWeights:Object.fromEntries(exercises.map(e=>[e.id,e.base]))},sessions:[]});
let db=loadDb(), completed=JSON.parse(localStorage.getItem('fittrack-today')||'[]'), activeIndex=null;
function loadDb(){try{const raw=localStorage.getItem(DB_KEY);if(raw)return normalize(JSON.parse(raw));const old=JSON.parse(localStorage.getItem(LEGACY_KEY)||'[]');const d=defaultDb();d.sessions=old.map(x=>({id:crypto.randomUUID?crypto.randomUUID():String(Date.now()),date:x.date,startedAt:x.date+'T00:00:00',finishedAt:x.date+'T00:00:00',durationMinutes:x.minutes||0,completedExercises:(x.exerciseIndexes||[]).map(i=>({exerciseId:exercises[i]?.id,setsCompleted:exercises[i]?.sets||0,reps:exercises[i]?.reps||'',weightKg:Number(localStorage.getItem('weight-'+i)||exercises[i]?.base||0)}))}));saveDb(d);return d}catch{return defaultDb()}}
function normalize(d){return {...defaultDb(),...d,settings:{...defaultDb().settings,...(d.settings||{})},sessions:Array.isArray(d.sessions)?d.sessions:[]}}
function saveDb(d=db){d.updatedAt=new Date().toISOString();db=d;localStorage.setItem(DB_KEY,JSON.stringify(d))}
function saveUi(){localStorage.setItem('fittrack-today',JSON.stringify(completed))}
function todayKey(){return new Date().toLocaleDateString('en-CA')}
function fmtDate(d){return new Intl.DateTimeFormat('th-TH',{day:'numeric',month:'short',year:'numeric'}).format(new Date(d))}
function weightOf(e){return Number(db.settings.baseWeights[e.id]??e.base)}
function renderWorkout(){
 $('#workoutList').innerHTML=exercises.map((e,i)=>`<article class="workout-card ${activeIndex===i?'focused':''}"><div class="workout-number">${e.icon}</div><div><h3>${e.thai}</h3><p>${e.name}</p><div class="workout-meta"><span class="chip strong-chip">${e.sets} เซ็ต</span><span class="chip">${e.reps}</span><span class="chip">Base ${weightOf(e)} kg</span></div><div class="set-preview">${Array.from({length:e.sets},(_,s)=>`<span class="set-dot ${completed.includes(i)?'done':''}">Set ${s+1}</span>`).join('')}</div></div><div class="workout-controls"><button class="start-btn" data-start="${i}">${activeIndex===i?'กำลังทำ':'เริ่มท่า'}</button><label>น้ำหนักที่ใช้ (kg)<input type="number" min="0" step="0.5" value="${weightOf(e)||''}" data-weight="${i}" ${e.unit==='bodyweight'?'disabled':''}></label><label>ทำแล้ว (ครั้ง/วินาที)<input type="text" value="${e.reps}" data-reps="${i}"></label></div></article>`).join('');
 $$('[data-weight]').forEach(x=>x.addEventListener('change',e=>{const i=+e.target.dataset.weight;db.settings.baseWeights[exercises[i].id]=Number(e.target.value)||0;saveDb();renderWorkout();renderSettings()}));
 $$('[data-start]').forEach(b=>b.onclick=()=>{activeIndex=+b.dataset.start;renderWorkout();renderActiveExercise();document.querySelector('.focused')?.scrollIntoView({behavior:'smooth',block:'center'})});
 $$('[data-reps]').forEach(x=>x.addEventListener('change',e=>{const i=+e.target.dataset.reps;localStorage.setItem('fittrack-reps-'+exercises[i].id,e.target.value)}));
}
function renderActiveExercise(){const box=$('#activeExercise');if(activeIndex===null){box.innerHTML='<div class="active-empty"><span>READY</span><strong>เลือกท่าที่จะเริ่ม</strong><p>กด “เริ่มท่า” แล้วระบบจะแสดงท่า จำนวนครั้ง และน้ำหนัก Base ที่คุณตั้งไว้</p></div>';return}const e=exercises[activeIndex];box.innerHTML=`<div class="active-card"><div><span class="tag">กำลังออก · ${e.icon}</span><h3>${e.thai}</h3><p>${e.name}</p></div><div class="active-metrics"><div><small>จำนวนครั้ง</small><b>${e.reps}</b></div><div><small>จำนวนเซ็ต</small><b>${e.sets}</b></div><div><small>น้ำหนัก Base</small><b>${e.unit==='bodyweight'?'ตัวเอง':weightOf(e)+' kg'}</b></div></div><button class="primary" data-complete="${activeIndex}">✓ ทำท่านี้เสร็จ</button></div>`;box.querySelector('[data-complete]').onclick=()=>{if(!completed.includes(activeIndex))completed=[...completed,activeIndex];saveUi();renderAll();activeIndex=null;renderWorkout();renderActiveExercise()}}
function renderDashboard(){
 const rows=exercises.map((e,i)=>`<div class="exercise-row"><div class="exercise-icon">${e.icon}</div><div class="exercise-info"><b>${e.thai}</b><small>${e.sets} เซ็ต · ${e.reps} · ${e.unit==='bodyweight'?'น้ำหนักตัว':weightOf(e)+' kg'}</small></div><button class="check ${completed.includes(i)?'done':''}" data-check="${i}">${completed.includes(i)?'✓':''}</button></div>`).join('');$('#dashboardExercises').innerHTML=rows;
 $$('[data-check]').forEach(b=>b.onclick=()=>{const i=+b.dataset.check;completed=completed.includes(i)?completed.filter(x=>x!==i):[...completed,i];saveUi();renderAll()});
 const pct=Math.round(completed.length/exercises.length*100), workouts=db.sessions.length, mins=db.sessions.reduce((a,x)=>a+(x.durationMinutes||0),0), sets=db.sessions.reduce((a,x)=>a+(x.completedExercises||[]).reduce((n,y)=>n+(y.setsCompleted||0),0),0);
 $('#heroCount').textContent=pct+'%';$('#statWorkouts').textContent=workouts;$('#statMinutes').textContent=mins;$('#statSets').textContent=sets;$('#statStreak').textContent=calcStreak();$('#goalText').textContent=Math.min(workouts,4)+' / 4 วัน';$('#goalBar').style.width=Math.min(workouts/4*100,100)+'%';
 const week=$('#week'), dayNames=['จ','อ','พ','พฤ','ศ','ส','อา'], now=new Date(), monday=new Date(now);monday.setDate(now.getDate()-((now.getDay()+6)%7));const dates=new Set(db.sessions.map(x=>x.date));week.innerHTML=dayNames.map((d,i)=>{const dt=new Date(monday);dt.setDate(monday.getDate()+i);const k=dt.toLocaleDateString('en-CA');return `<div class="day ${dates.has(k)?'done':''}"><b>${d}</b><span>${dates.has(k)?'✓':'—'}</span></div>`}).join('');
}
function calcStreak(){const dates=[...new Set(db.sessions.map(x=>x.date))].sort().reverse();let streak=0,cur=new Date();for(let i=0;i<dates.length;i++){const target=new Date(cur);target.setDate(cur.getDate()-i);if(dates[i]===target.toLocaleDateString('en-CA'))streak++;else break}return streak}
function renderHistory(){const box=$('#historyList');if(!db.sessions.length){box.innerHTML='<div class="empty">ยังไม่มีประวัติ — เริ่ม Workout วันนี้ได้เลย</div>';return}box.innerHTML=[...db.sessions].reverse().map(x=>`<div class="history-item"><div><b>Full Body Workout</b><span>${fmtDate(x.date)} · ${(x.completedExercises||[]).reduce((a,e)=>a+e.setsCompleted,0)} เซ็ต · ${x.durationMinutes||0} นาที · ${(x.completedExercises||[]).length} ท่า</span></div><strong>✓ เสร็จแล้ว</strong></div>`).join('')}
function renderProgress(){const total=db.sessions.length;const sets=db.sessions.reduce((a,x)=>a+(x.completedExercises||[]).reduce((n,y)=>n+y.setsCompleted,0),0);const mins=db.sessions.reduce((a,x)=>a+(x.durationMinutes||0),0);const completedCount=db.sessions.reduce((a,x)=>a+(x.completedExercises||[]).length,0);$('#progressWorkouts').textContent=total;$('#progressMinutes').textContent=mins;$('#progressSets').textContent=sets;$('#progressRate').textContent=total?Math.round(completedCount/(total*exercises.length)*100)+'%':'0%';$('#exerciseProgress').innerHTML=exercises.map(e=>{const rows=db.sessions.flatMap(x=>x.completedExercises||[]).filter(x=>x.exerciseId===e.id), n=rows.length, pct=total?Math.round(n/total*100):0,last=rows.at(-1);return `<div class="progress-line"><header><span>${e.thai}</span><b>${pct}% ${last?`· ล่าสุด ${last.weightKg||0} kg`:''}</b></header><div class="progress"><i style="width:${pct}%"></i></div></div>`}).join('')}
function renderSettings(){$('#weightSettings').innerHTML=exercises.map(e=>`<label class="setting-row"><span><b>${e.thai}</b><small>${e.unit==='bodyweight'?'น้ำหนักตัว':`น้ำหนัก Base สำหรับเริ่มต้น`}</small></span>${e.unit==='bodyweight'?'<strong>Bodyweight</strong>':`<div class="kg-input"><input type="number" min="0" step="0.5" value="${weightOf(e)}" data-base="${e.id}"><b>kg</b></div>`}</label>`).join('');$$('[data-base]').forEach(x=>x.onchange=()=>{db.settings.baseWeights[x.dataset.base]=Number(x.value)||0;saveDb();renderWorkout();renderDashboard();renderActiveExercise()});$('#dataStatus').textContent=`เก็บ ${db.sessions.length} workout session · อัปเดตล่าสุด ${new Date(db.updatedAt).toLocaleString('th-TH')}`}
function exportJson(){const payload={...db,exportedAt:new Date().toISOString()};const blob=new Blob([JSON.stringify(payload,null,2)],{type:'application/json'}),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download=`fittrack-backup-${todayKey()}.json`;a.click();URL.revokeObjectURL(url)}
function importJson(file){const reader=new FileReader();reader.onload=()=>{try{const incoming=normalize(JSON.parse(reader.result));if(!Array.isArray(incoming.sessions))throw Error();saveDb(incoming);completed=[];saveUi();renderAll();renderSettings();alert('กู้คืนข้อมูลจาก JSON สำเร็จ');}catch{alert('ไฟล์ JSON ไม่ถูกต้องหรือไม่ใช่ข้อมูล FitTrack')}};reader.readAsText(file)}
function resetData(){if(!confirm('ยืนยันล้างประวัติ Workout ทั้งหมด? ควร Export JSON ก่อน'))return;db=defaultDb();saveDb();completed=[];saveUi();renderAll();renderSettings()}
function renderAll(){renderDashboard();renderHistory();renderProgress();renderSettings()}
function nav(){$$('.nav-item').forEach(b=>b.onclick=()=>go(b.dataset.section));$$('[data-go]').forEach(b=>b.onclick=()=>go(b.dataset.go))}
function go(id){$$('.section').forEach(s=>s.classList.remove('active-section'));$('#'+id).classList.add('active-section');$$('.nav-item').forEach(b=>b.classList.toggle('active',b.dataset.section===id));$('#pageTitle').textContent={dashboard:'Dashboard',workout:'Workout วันนี้',history:'ประวัติ',progress:'Progress',settings:'ตั้งค่า & ข้อมูล'}[id];window.scrollTo({top:0,behavior:'smooth'});if(id==='workout'){renderWorkout();renderActiveExercise()}}
$('#finishWorkout').onclick=()=>{if(!completed.length){alert('ทำอย่างน้อย 1 ท่าก่อนบันทึกครับ');return}const date=todayKey(),startedAt=new Date(Date.now()-completed.length*7*60000).toISOString(),finishedAt=new Date().toISOString();const details=completed.map(i=>{const e=exercises[i];return {exerciseId:e.id,name:e.name,setsCompleted:e.sets,reps:localStorage.getItem('fittrack-reps-'+e.id)||e.reps,weightKg:e.unit==='bodyweight'?0:weightOf(e)}});const entry={id:crypto.randomUUID?crypto.randomUUID():String(Date.now()),date,startedAt,finishedAt,durationMinutes:completed.length*7,completedExercises:details};const idx=db.sessions.findIndex(x=>x.date===date);if(idx>=0)db.sessions[idx]=entry;else db.sessions.push(entry);saveDb();completed=[];saveUi();activeIndex=null;renderAll();renderWorkout();renderActiveExercise();alert('บันทึก Workout วันนี้เรียบร้อยแล้ว');go('dashboard')};
$('#exportData').onclick=exportJson;$('#importData').onchange=e=>e.target.files[0]&&importJson(e.target.files[0]);$('#resetData').onclick=resetData;$('#today').textContent=new Intl.DateTimeFormat('th-TH',{weekday:'long',day:'numeric',month:'long'}).format(new Date());
nav();renderWorkout();renderActiveExercise();renderAll();