const exercises=[
 {id:'goblet-squat',name:'Goblet Squat',thai:'Goblet Squat',sets:3,reps:'10–12',base:8,unit:'kg',icon:'01',motion:'squat'},
 {id:'rdl',name:'Dumbbell Romanian Deadlift',thai:'Dumbbell RDL',sets:3,reps:'10–12',base:8,unit:'kg',icon:'02',motion:'hinge'},
 {id:'floor-press',name:'Dumbbell Floor Press',thai:'Dumbbell Floor Press',sets:3,reps:'10–12',base:6,unit:'kg',icon:'03',motion:'press'},
 {id:'row',name:'One-arm Dumbbell Row',thai:'One-arm Row',sets:3,reps:'10 / ข้าง',base:8,unit:'kg',icon:'04',motion:'row'},
 {id:'shoulder-press',name:'Dumbbell Shoulder Press',thai:'Shoulder Press',sets:3,reps:'8–10',base:6,unit:'kg',icon:'05',motion:'press'},
 {id:'plank',name:'Plank',thai:'Plank',sets:3,reps:'30–45 วินาที',base:0,unit:'bodyweight',icon:'06',motion:'plank'}
];
const DB_KEY='fittrack-db-v2',LEGACY_KEY='fittrack-history';
const $=s=>document.querySelector(s),$$=s=>document.querySelectorAll(s);
const defaultDb=()=>({schemaVersion:2,createdAt:new Date().toISOString(),updatedAt:new Date().toISOString(),settings:{baseWeights:Object.fromEntries(exercises.map(e=>[e.id,e.base]))},sessions:[]});
let db=loadDb(),completed=JSON.parse(localStorage.getItem('fittrack-today')||'[]'),activeIndex=null,sessionSets=[];
function loadDb(){try{const raw=localStorage.getItem(DB_KEY);if(raw)return normalize(JSON.parse(raw));const old=JSON.parse(localStorage.getItem(LEGACY_KEY)||'[]'),d=defaultDb();d.sessions=old.map(x=>({id:Date.now()+'-'+Math.random(),date:x.date,durationMinutes:x.minutes||0,completedExercises:(x.exerciseIndexes||[]).map(i=>({exerciseId:exercises[i]?.id,name:exercises[i]?.name,setsCompleted:exercises[i]?.sets||0,reps:exercises[i]?.reps||'',weightKg:Number(localStorage.getItem('weight-'+i)||exercises[i]?.base||0)}))}));saveDb(d);return d}catch{return defaultDb()}}
function normalize(d){const base=defaultDb();return {...base,...d,settings:{...base.settings,...(d.settings||{}),baseWeights:{...base.settings.baseWeights,...(d.settings?.baseWeights||{})}},sessions:Array.isArray(d.sessions)?d.sessions:[]}}
function saveDb(d=db){d.updatedAt=new Date().toISOString();db=d;localStorage.setItem(DB_KEY,JSON.stringify(d))}
function saveUi(){localStorage.setItem('fittrack-today',JSON.stringify(completed))}
function todayKey(){return new Date().toLocaleDateString('en-CA')}
function fmtDate(d){return new Intl.DateTimeFormat('th-TH',{day:'numeric',month:'short',year:'numeric'}).format(new Date(d+'T00:00:00'))}
function weightOf(e){return Number(db.settings.baseWeights[e.id]??e.base)}
function currentDone(i){const row=sessionSets.find(x=>x.exerciseId===exercises[i].id);return row?.setsCompleted||0}
function motionMarkup(e){return `<div class="motion-scene motion-${e.motion}" aria-label="ภาพเคลื่อนไหวสาธิต ${e.thai}"><div class="motion-glow"></div><div class="motion-figure"><i class="head"></i><i class="torso"></i><i class="arm a1"></i><i class="arm a2"></i><i class="leg l1"></i><i class="leg l2"></i></div><div class="motion-floor"></div><span class="motion-label">DEMO</span></div>`}
function renderWorkout(){const e=activeIndex===null?exercises[0]:exercises[activeIndex];const i=activeIndex===null?0:activeIndex;const done=currentDone(i);$('#workoutList').innerHTML=`<article class="trainer-card"><div class="trainer-header"><button class="icon-btn" id="prevExercise">←</button><div><small>FULL BODY · ${String(i+1).padStart(2,'0')} / ${exercises.length}</small><strong>${done>=e.sets?'ท่าครบแล้ว':'กำลังฝึก'}</strong></div><button class="icon-btn" id="nextExercise">→</button></div>${motionMarkup(e)}<div class="trainer-title"><span class="tag">${e.unit==='bodyweight'?'CORE':'STRENGTH'}</span><h2>${e.thai}</h2><p>${e.name}</p></div><div class="trainer-stats"><div><small>เป้าหมาย</small><b>${e.reps}</b><span>ครั้ง</span></div><div><small>SET</small><b>${Math.min(done+1,e.sets)}</b><span>/ ${e.sets}</span></div><div><small>WEIGHT</small><b>${e.unit==='bodyweight'?'BODY':weightOf(e)}</b><span>${e.unit==='bodyweight'?'':'kg'}</span></div></div>${e.unit==='bodyweight'?'':`<div class="kg-stepper"><button data-kg="-0.5">−</button><div><small>น้ำหนักวันนี้</small><strong>${weightOf(e).toFixed(1)} kg</strong></div><button data-kg="0.5">+</button></div>`}<div class="set-dots">${Array.from({length:e.sets},(_,s)=>`<span class="${s<done?'done':''}"><i>${s<done?'✓':s+1}</i> Set ${s+1}</span>`).join('')}</div><button class="primary trainer-action" id="completeSet">${done>=e.sets?'✓ ท่านี้เสร็จแล้ว':`ทำ SET ${done+1} เสร็จ`}</button>${done>=e.sets&&i<exercises.length-1?'<button class="next-action" id="nextAction">ไปท่าถัดไป →</button>':''}<div class="coach-tip"><b>โฟกัส</b><span>${tipFor(e)}</span></div></article>`;
 $('#prevExercise').onclick=()=>{activeIndex=Math.max(0,i-1);renderWorkout()};$('#nextExercise').onclick=()=>{activeIndex=Math.min(exercises.length-1,i+1);renderWorkout()};$('#nextAction')?.addEventListener('click',()=>{activeIndex=Math.min(exercises.length-1,i+1);renderWorkout()});$('#completeSet').onclick=()=>completeSet(i);$$('[data-kg]').forEach(b=>b.onclick=()=>{db.settings.baseWeights[e.id]=Math.max(0,Math.round((weightOf(e)+Number(b.dataset.kg))*10)/10);saveDb();renderWorkout();renderDashboard();renderSettings()})}
function tipFor(e){return {squat:'เข่าไปตามแนวปลายเท้า หลังตรง ลงช้า ดันพื้นกลับขึ้น',hinge:'ดันสะโพกไปด้านหลัง รักษาหลังเป็นกลาง บีบก้นตอนขึ้น',press:'เกร็งลำตัว ดันขึ้นตรง ๆ และควบคุมตอนลง',row:'หลังนิ่ง ดึงศอกไปด้านหลัง บีบสะบัก',plank:'เกร็งหน้าท้อง ให้ศีรษะ หลัง และสะโพกเป็นแนวเดียว'}[e.motion]}
function completeSet(i){const e=exercises[i];let row=sessionSets.find(x=>x.exerciseId===e.id);if(!row){row={exerciseId:e.id,name:e.name,setsCompleted:0,totalSets:e.sets,reps:e.reps,weightKg:e.unit==='bodyweight'?0:weightOf(e),sets:[]}}if(row.setsCompleted>=e.sets)return;row.setsCompleted++;row.sets.push({set:row.setsCompleted,reps:e.reps,weightKg:row.weightKg,completedAt:new Date().toISOString()});if(!sessionSets.includes(row))sessionSets.push(row);completed=[...new Set([...completed,i])];saveUi();renderWorkout();renderDashboard();if(row.setsCompleted>=e.sets&&i<exercises.length-1){setTimeout(()=>{activeIndex=i+1;renderWorkout()},450)}}
function finishSession(){if(!sessionSets.length){alert('เริ่มอย่างน้อย 1 เซ็ตก่อนบันทึกครับ');return}const date=todayKey(),details=sessionSets.map(x=>({...x,sets:x.sets.map(s=>({...s}))})),entry={id:Date.now()+'-'+Math.random(),date,startedAt:sessionSets[0].sets[0]?.completedAt||new Date().toISOString(),finishedAt:new Date().toISOString(),durationMinutes:Math.max(1,sessionSets.reduce((a,x)=>a+x.setsCompleted,0)*4),completedExercises:details,setsCompleted:details.reduce((a,x)=>a+x.setsCompleted,0)};const idx=db.sessions.findIndex(x=>x.date===date);if(idx>=0)db.sessions[idx]=entry;else db.sessions.push(entry);saveDb();sessionSets=[];completed=[];activeIndex=null;saveUi();renderAll();renderWorkout();alert('Workout บันทึกเรียบร้อย ข้อมูลพร้อมใช้ทำรายงานแล้ว');go('dashboard')}
function renderDashboard(){const today=db.sessions.find(x=>x.date===todayKey()),liveSets=sessionSets.reduce((a,x)=>a+x.setsCompleted,0),pct=sessionSets.length?Math.round(liveSets/sessionSets.reduce((a,x)=>a+x.totalSets,0)*100):today?Math.round((today.completedExercises?.length||0)/exercises.length*100):0;$('#dashboardExercises').innerHTML=exercises.map((e,i)=>{const live=sessionSets.find(x=>x.exerciseId===e.id),saved=today?.completedExercises?.find(x=>x.exerciseId===e.id),done=live?.setsCompleted||saved?.setsCompleted||0;return `<div class="exercise-row"><div class="exercise-icon">${e.icon}</div><div class="exercise-info"><b>${e.thai}</b><small>${done}/${e.sets} เซ็ต · ${e.reps} · ${e.unit==='bodyweight'?'น้ำหนักตัว':weightOf(e)+' kg'}</small></div><span class="mini-status ${done>=e.sets?'done':''}">${done>=e.sets?'✓':'○'}</span></div>`}).join('');const workouts=db.sessions.length,mins=db.sessions.reduce((a,x)=>a+(x.durationMinutes||0),0),sets=db.sessions.reduce((a,x)=>a+(x.setsCompleted||0),0);$('#heroCount').textContent=pct+'%';$('#statWorkouts').textContent=workouts;$('#statMinutes').textContent=mins;$('#statSets').textContent=sets;$('#statStreak').textContent=calcStreak();$('#goalText').textContent=Math.min(workouts,4)+' / 4 วัน';$('#goalBar').style.width=Math.min(workouts/4*100,100)+'%';const now=new Date(),monday=new Date(now);monday.setDate(now.getDate()-((now.getDay()+6)%7));const dates=new Set(db.sessions.map(x=>x.date));$('#week').innerHTML=['จ','อ','พ','พฤ','ศ','ส','อา'].map((d,i)=>{const dt=new Date(monday);dt.setDate(monday.getDate()+i);const k=dt.toLocaleDateString('en-CA');return `<div class="day ${dates.has(k)?'done':''}"><b>${d}</b><span>${dates.has(k)?'✓':'—'}</span></div>`}).join('')}
function calcStreak(){const dates=[...new Set(db.sessions.map(x=>x.date))].sort().reverse();let n=0;for(let i=0;i<dates.length;i++){const d=new Date();d.setDate(d.getDate()-i);if(dates[i]===d.toLocaleDateString('en-CA'))n++;else break}return n}
function renderHistory(){const box=$('#historyList');if(!db.sessions.length){box.innerHTML='<div class="empty">ยังไม่มีประวัติ — เริ่ม Workout วันนี้ได้เลย</div>';return}box.innerHTML=[...db.sessions].reverse().map(x=>`<div class="history-item"><div><b>Full Body Workout</b><span>${fmtDate(x.date)} · ${x.setsCompleted||0} เซ็ต · ${x.durationMinutes||0} นาที · ${(x.completedExercises||[]).length} ท่า</span></div><strong>✓ บันทึกแล้ว</strong></div>`).join('')}
function renderProgress(){const total=db.sessions.length,sets=db.sessions.reduce((a,x)=>a+(x.setsCompleted||0),0),mins=db.sessions.reduce((a,x)=>a+(x.durationMinutes||0),0),completedCount=db.sessions.reduce((a,x)=>a+(x.completedExercises||[]).filter(e=>e.setsCompleted>0).length,0);$('#progressWorkouts').textContent=total;$('#progressMinutes').textContent=mins;$('#progressSets').textContent=sets;$('#progressRate').textContent=total?Math.round(completedCount/(total*exercises.length)*100)+'%':'0%';$('#exerciseProgress').innerHTML=exercises.map(e=>{const rows=db.sessions.flatMap(x=>x.completedExercises||[]).filter(x=>x.exerciseId===e.id),n=rows.length,pct=total?Math.round(n/total*100):0,last=rows.at(-1);return `<div class="progress-line"><header><span>${e.thai}</span><b>${pct}% ${last?`· ล่าสุด ${last.weightKg||0} kg`:''}</b></header><div class="progress"><i style="width:${pct}%"></i></div></div>`}).join('')}
function renderSettings(){$('#weightSettings').innerHTML=exercises.map(e=>`<label class="setting-row"><span><b>${e.thai}</b><small>${e.unit==='bodyweight'?'น้ำหนักตัว':'น้ำหนัก Base สำหรับเริ่มต้น'}</small></span>${e.unit==='bodyweight'?'<strong>Bodyweight</strong>':`<div class="kg-input"><input type="number" min="0" step="0.5" value="${weightOf(e)}" data-base="${e.id}"><b>kg</b></div>`}</label>`).join('');$$('[data-base]').forEach(x=>x.onchange=()=>{db.settings.baseWeights[x.dataset.base]=Math.max(0,Number(x.value)||0);saveDb();renderWorkout();renderDashboard()});$('#dataStatus').textContent=`เก็บ ${db.sessions.length} workout session · อัปเดตล่าสุด ${new Date(db.updatedAt).toLocaleString('th-TH')}`}
function exportJson(){const payload={...db,exportedAt:new Date().toISOString()};const blob=new Blob([JSON.stringify(payload,null,2)],{type:'application/json'}),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download=`fittrack-backup-${todayKey()}.json`;a.click();URL.revokeObjectURL(url)}
function importJson(file){const r=new FileReader();r.onload=()=>{try{const incoming=normalize(JSON.parse(r.result));saveDb(incoming);completed=[];sessionSets=[];saveUi();renderAll();alert('กู้คืนข้อมูลจาก JSON สำเร็จ')}catch{alert('ไฟล์ JSON ไม่ถูกต้อง')}};r.readAsText(file)}
function resetData(){if(!confirm('ยืนยันล้างประวัติทั้งหมด? แนะนำ Export JSON ก่อน'))return;db=defaultDb();saveDb();completed=[];sessionSets=[];saveUi();renderAll()}
function renderAll(){renderDashboard();renderHistory();renderProgress();renderSettings()}
function nav(){$$('.nav-item').forEach(b=>b.onclick=()=>go(b.dataset.section));$$('[data-go]').forEach(b=>b.onclick=()=>go(b.dataset.go))}
function go(id){$$('.section').forEach(s=>s.classList.remove('active-section'));$('#'+id).classList.add('active-section');$$('.nav-item').forEach(b=>b.classList.toggle('active',b.dataset.section===id));$('#pageTitle').textContent={dashboard:'Dashboard',workout:'Workout วันนี้',history:'ประวัติ',progress:'Progress',settings:'ตั้งค่า & ข้อมูล'}[id];if(id==='workout')renderWorkout();window.scrollTo({top:0,behavior:'smooth'})}
$('#finishWorkout').onclick=finishSession;$('#exportData').onclick=exportJson;$('#importData').onchange=e=>e.target.files[0]&&importJson(e.target.files[0]);$('#resetData').onclick=resetData;$('#today').textContent=new Intl.DateTimeFormat('th-TH',{weekday:'long',day:'numeric',month:'long'}).format(new Date());nav();renderWorkout();renderAll();